# -*- coding: utf-8 -*-
"""Каталог TOVMASYAN Jeweler, собранный по фотографиям изделий.
Каждая запись описывает то, что действительно видно на снимке."""

U = '/home/user/uploads/photo_{}_2026-10-09_23-45-52.jpg'

# материал / камни: общий словарь, чтобы переводы не разрастались
MAT_Y = 'Золото 585 / 750'
MAT_W = 'Белое золото 585'
MAT_R = 'Красное золото 585'
ST_PAVE = 'Бриллианты или фианиты, паве'
ST_CENTER = 'Центральный камень и паве'
ST_SOLO = 'Один центральный камень'
ST_LINE = 'Дорожка камней по всей длине'

PRODUCTS = [
    # ---------------------------- крестики ----------------------------
    dict(src=14, id='cross-lumiere', cat='pendants', label='Подвески', col='Sacred Light',
         mat=MAT_Y, st=ST_CENTER, size='Высота ок. 25 мм',
         name=dict(ru='Крестик Lumière', hy='Խաչ Lumière', en='Lumière Cross'),
         short=dict(ru='Тонкий крестик с центральным камнем и дорожкой паве.',
                    hy='Նուրբ խաչ՝ կենտրոնական քարով և պավե շարքով.',
                    en='A slender cross with a centre stone and a pavé line.'),
         desc=dict(ru='Лучи крестика плавно сужаются к центру, где закреплен крупный круглый камень. Нижний и боковые лучи усыпаны дорожкой мелких камней, поэтому изделие сияет даже при мягком свете. Поставляется на тонкой якорной цепочке.',
                   hy='Խաչի թևերը սահուն նեղանում են դեպի կենտրոն, որտեղ ամրացված է խոշոր կլոր քար։ Ստորին և կողային թևերը զարդարված են մանր քարերի շարքով, այդ պատճառով զարդը փայլում է նույնիսկ մեղմ լույսի տակ։ Մատակարարվում է բարակ շղթայով։',
                   en='The arms taper softly towards the centre, where a larger round stone is set. The lower and side arms carry a line of small stones, so the piece sparkles even in soft light. Supplied on a fine cable chain.'),
         tags=dict(ru=['крестик', 'паве', 'подарок'], hy=['խաչ', 'պավե', 'նվեր'], en=['cross', 'pavé', 'gift'])),

    dict(src=15, id='cross-petale', cat='pendants', label='Подвески', col='Sacred Light',
         mat=MAT_Y, st=ST_CENTER, size='Высота ок. 24 мм',
         name=dict(ru='Крестик Pétale', hy='Խաչ Pétale', en='Pétale Cross'),
         short=dict(ru='Крестик-цветок из четырех лепестков с паве.',
                    hy='Ծաղկաձև խաչ՝ չորս թերթիկով և պավեով.',
                    en='A flower-shaped cross of four pavé petals.'),
         desc=dict(ru='Лучи выполнены в форме мягких лепестков-маркиз, внутри каждого — ряд мелких камней, а в центре закреплен более крупный круглый камень. Благодаря округлым линиям крестик смотрится женственно и деликатно.',
                   hy='Թևերը պատրաստված են մարկիզ-թերթիկների տեսքով, յուրաքանչյուրի ներսում՝ մանր քարերի շարք, իսկ կենտրոնում ամրացված է ավելի խոշոր կլոր քար։ Կլորացված գծերի շնորհիվ խաչը երևում է կանացի և նրբագեղ։',
                   en='The arms are shaped as soft marquise petals, each filled with a row of small stones, with a larger round stone in the centre. The rounded lines make the cross feminine and delicate.'),
         tags=dict(ru=['крестик', 'цветок', 'нежный'], hy=['խաչ', 'ծաղիկ', 'նուրբ'], en=['cross', 'flower', 'delicate'])),

    dict(src=16, id='cross-royal', cat='pendants', label='Подвески', col='Royal Detail',
         mat=MAT_Y, st=ST_CENTER, size='Высота ок. 28 мм',
         name=dict(ru='Крестик Royal', hy='Խաչ Royal', en='Royal Cross'),
         short=dict(ru='Фигурный крестик с тремя камнями на каждом конце.',
                    hy='Պատկերազարդ խաչ՝ երեք քարով յուրաքանչյուր ծայրին.',
                    en='A shaped cross with three stones at every tip.'),
         desc=dict(ru='Лучи расходятся резной «короной», и каждый конец увенчан тремя круглыми камнями, а центр отмечен крупной вставкой. Рельефное литье дает глубокие тени и подчеркивает классический, почти храмовый силуэт.',
                   hy='Թևերը բացվում են փորագրված «թագով», յուրաքանչյուր ծայր պսակված է երեք կլոր քարով, իսկ կենտրոնը նշված է խոշոր ներդիրով։ Ռելիեֆային ձուլումը տալիս է խորը ստվերներ և ընդգծում դասական ուրվագիծը։',
                   en='The arms open into a carved crown, each tip crowned with three round stones and the centre marked by a larger one. The relief casting gives deep shadows and underlines the classic silhouette.'),
         tags=dict(ru=['крестик', 'рельеф', 'классика'], hy=['խաչ', 'ռելիեֆ', 'դասական'], en=['cross', 'relief', 'classic'])),

    dict(src=17, id='cross-infinity', cat='pendants', label='Подвески', col='Signature Gold',
         mat=MAT_Y, st=ST_PAVE, size='Высота ок. 26 мм',
         name=dict(ru='Крестик Infinity', hy='Խաչ Infinity', en='Infinity Cross'),
         short=dict(ru='Переплетенные ленты золота с белым паве.',
                    hy='Ոսկու հյուսված ժապավեններ՝ սպիտակ պավեով.',
                    en='Interlaced gold ribbons set with white pavé.'),
         desc=dict(ru='Две золотые ленты плавно перекрещиваются в центре, образуя мягкий силуэт креста без острых углов. Внутренняя часть каждой ленты закреплена мелкими камнями в белом родировании — получается контраст теплого золота и холодного блеска.',
                   hy='Երկու ոսկե ժապավեններ սահուն խաչվում են կենտրոնում՝ ստեղծելով առանց սուր անկյունների մեղմ ուրվագիծ։ Յուրաքանչյուր ժապավենի ներսը ամրացված է մանր քարերով՝ սպիտակ ծածկույթով, ինչը տալիս է տաք ոսկու և սառը փայլի հակադրություն։',
                   en='Two gold ribbons cross smoothly in the centre, forming a soft cross without sharp corners. The inner side of each ribbon is set with small stones in white rhodium, contrasting warm gold with cool sparkle.'),
         tags=dict(ru=['крестик', 'паве', 'современный'], hy=['խաչ', 'պավե', 'ժամանակակից'], en=['cross', 'pavé', 'modern'])),

    dict(src=18, id='cross-grand-rose', cat='pendants', label='Подвески', col='Royal Detail',
         mat=MAT_R, st=ST_PAVE, size='Высота ок. 38 мм',
         name=dict(ru='Крестик Grand', hy='Խաչ Grand', en='Grand Cross'),
         short=dict(ru='Крупный ажурный крест из красного золота в паве.',
                    hy='Խոշոր ажурային խաչ կարմիր ոսկուց՝ պավեով.',
                    en='A large openwork rose-gold cross in pavé.'),
         desc=dict(ru='Самая заметная модель линии: открытый контур каждого луча обведен дорожкой камней, внутри идет вторая, более тонкая линия, а центр собран из четырех крупных круглых вставок. Красное золото делает блеск теплым и мягким.',
                   hy='Գծի ամենաարտահայտիչ մոդելը՝ յուրաքանչյուր թևի բաց ուրվագիծը եզերված է քարերի շարքով, ներսում անցնում է երկրորդ՝ ավելի բարակ գիծը, իսկ կենտրոնը հավաքված է չորս խոշոր ներդիրից։ Կարմիր ոսկին փայլը դարձնում է տաք և մեղմ։',
                   en='The statement piece of the line: the open outline of every arm is traced with stones, a second finer line runs inside, and the centre is built from four larger round stones. Rose gold keeps the sparkle warm.'),
         tags=dict(ru=['крестик', 'красное золото', 'премиум'], hy=['խաչ', 'կարմիր ոսկի', 'պրեմիում'], en=['cross', 'rose gold', 'premium'])),

    dict(src=19, id='cross-classic', cat='pendants', label='Подвески', col='Classic Line',
         mat=MAT_Y, st=ST_SOLO, size='Высота ок. 32 мм',
         name=dict(ru='Крестик Classic', hy='Խաչ Classic', en='Classic Cross'),
         short=dict(ru='Гладкий полированный крестик с одним камнем.',
                    hy='Հարթ փայլեցված խաչ՝ մեկ քարով.',
                    en='A smooth polished cross with a single stone.'),
         desc=dict(ru='Строгая форма без лишнего декора: широкие полированные лучи с мягким скосом и единственный круглый камень в перекрестии. Такой крестик одинаково уместен и как повседневный, и как подарок на крестины.',
                   hy='Խիստ ձև՝ առանց ավելորդ դեկորի․ լայն փայլեցված թևեր մեղմ թեքությամբ և մեկ կլոր քար խաչման կետում։ Այսպիսի խաչը հարմար է և՛ ամենօրյա կրելու, և՛ մկրտության նվերի համար։',
                   en='A strict shape with no extra decoration: wide polished arms with a soft bevel and a single round stone at the crossing. Equally suited to everyday wear and to a christening gift.'),
         tags=dict(ru=['крестик', 'классика', 'на каждый день'], hy=['խաչ', 'դասական', 'ամենօրյա'], en=['cross', 'classic', 'everyday'])),

    # ---------------------------- колье ----------------------------
    dict(src=20, id='papillon-necklace', cat='chains', label='Колье', col='Papillon',
         mat=MAT_Y, st=ST_SOLO, size='Цепочка 40–45 см',
         name=dict(ru='Колье Papillon', hy='Վզնոց Papillon', en='Papillon Necklace'),
         short=dict(ru='Бабочка из гладкого золота с камнем в центре.',
                    hy='Թիթեռ հարթ ոսկուց՝ կենտրոնում քարով.',
                    en='A polished gold butterfly with a central stone.'),
         desc=dict(ru='Четыре вытянутых лепестка образуют силуэт бабочки, в центре — круглый камень в аккуратной глухой закрепке. Подвеска вшита в цепочку двумя точками, поэтому всегда лежит ровно и не переворачивается.',
                   hy='Չորս երկարավուն թերթիկներ կազմում են թիթեռի ուրվագիծ, կենտրոնում՝ կլոր քար կույր ամրակում։ Կախազարդը ամրացված է շղթային երկու կետով, ուստի միշտ հարթ է դասավորվում։',
                   en='Four elongated petals form a butterfly, with a round stone in a neat bezel at the centre. The pendant is attached to the chain at two points, so it always lies flat.'),
         tags=dict(ru=['бабочка', 'колье', 'минимализм'], hy=['թիթեռ', 'վզնոց', 'մինիմալիզմ'], en=['butterfly', 'necklace', 'minimal'])),

    dict(src=22, id='fleur-necklace', cat='chains', label='Колье', col='Fleur',
         mat=MAT_R, st=ST_PAVE, size='Цепочка 40–45 см',
         name=dict(ru='Колье Fleur', hy='Վզնոց Fleur', en='Fleur Necklace'),
         short=dict(ru='Цветок из пяти лепестков, полностью покрытых камнями.',
                    hy='Հնգաթերթ ծաղիկ՝ ամբողջությամբ քարերով.',
                    en='A five-petal flower fully covered with stones.'),
         desc=dict(ru='Каждый лепесток плотно закреплен мелкими камнями, между ними видны тонкие линии красного золота, а сердцевина отмечена одним камнем покрупнее. Цветок закреплен на цепочке двумя петлями и красиво ложится в ямку ключиц.',
                   hy='Յուրաքանչյուր թերթիկ խիտ ամրացված է մանր քարերով, նրանց միջև երևում են կարմիր ոսկու բարակ գծեր, իսկ միջուկը նշված է ավելի խոշոր քարով։ Ծաղիկը ամրացված է շղթային երկու օղակով։',
                   en='Every petal is densely set with small stones, thin lines of rose gold showing between them, and the heart is marked by one larger stone. The flower hangs from two loops and sits beautifully at the collarbone.'),
         tags=dict(ru=['цветок', 'колье', 'красное золото'], hy=['ծաղիկ', 'վզնոց', 'կարմիր ոսկի'], en=['flower', 'necklace', 'rose gold'])),

    dict(src=24, id='duo-papillon-necklace', cat='chains', label='Колье', col='Papillon',
         mat=MAT_W, st=ST_PAVE, size='Цепочка 40–45 см',
         name=dict(ru='Колье Duo Papillon', hy='Վզնոց Duo Papillon', en='Duo Papillon Necklace'),
         short=dict(ru='Две ажурные бабочки из белого золота.',
                    hy='Երկու ажурային թիթեռ սպիտակ ոսկուց.',
                    en='Two openwork white-gold butterflies.'),
         desc=dict(ru='Контуры двух бабочек выложены дорожками камней и соединены так, будто одна догоняет другую. Внутри крыльев пусто — за счет этого украшение выглядит легким и почти невесомым на коже.',
                   hy='Երկու թիթեռների ուրվագծերը շարված են քարերով և միացված են այնպես, կարծես մեկը հասնում է մյուսին։ Թևերի ներսը բաց է, ինչի շնորհիվ զարդը թվում է թեթև և գրեթե անկշիռ։',
                   en='The outlines of two butterflies are traced with stones and joined as if one were following the other. The wings are left open, which makes the piece look light and almost weightless.'),
         tags=dict(ru=['бабочка', 'белое золото', 'колье'], hy=['թիթեռ', 'սպիտակ ոսկի', 'վզնոց'], en=['butterfly', 'white gold', 'necklace'])),

    dict(src=25, id='halo-necklace', cat='chains', label='Колье', col='Evening Shine',
         mat=MAT_Y, st=ST_CENTER, size='Цепочка 40–45 см',
         name=dict(ru='Колье Halo', hy='Վզնոց Halo', en='Halo Necklace'),
         short=dict(ru='Крупный круглый камень в обрамлении halo.',
                    hy='Խոշոր կլոր քար՝ halo շրջանակում.',
                    en='A large round stone in a halo setting.'),
         desc=dict(ru='Главный камень бриллиантовой огранки удерживают четыре золотые лапки, а по кругу его обрамляет дорожка мелких вставок — классический halo, который зрительно увеличивает центр и усиливает блеск. Подвеска скользит по цепочке и всегда оказывается по центру.',
                   hy='Հիմնական քարը պահում են չորս ոսկե ճանկեր, իսկ շուրջը եզերում է մանր ներդիրների շարքը՝ դասական halo, որը տեսողականորեն մեծացնում է կենտրոնը և ուժեղացնում փայլը։ Կախազարդը սահում է շղթայով և միշտ հայտնվում կենտրոնում։',
                   en='Four gold prongs hold the brilliant-cut main stone, framed by a ring of small stones — the classic halo that visually enlarges the centre and boosts the sparkle. The pendant glides on the chain and always centres itself.'),
         tags=dict(ru=['halo', 'колье', 'вечерний образ'], hy=['halo', 'վզնոց', 'երեկոյան'], en=['halo', 'necklace', 'evening'])),

    dict(src=27, id='arc-marquise-necklace', cat='chains', label='Колье', col='Signature Gold',
         mat=MAT_Y, st=ST_SOLO, size='Цепочка 40–45 см',
         name=dict(ru='Колье Arc Marquise', hy='Վզնոց Arc Marquise', en='Arc Marquise Necklace'),
         short=dict(ru='Золотая дуга с камнем огранки маркиз.',
                    hy='Ոսկե աղեղ՝ մարկիզ հղկվածքի քարով.',
                    en='A gold arc with a marquise-cut stone.'),
         desc=dict(ru='Гладкая золотая дуга мягко повторяет линию шеи, а в ее нижней точке вертикально закреплен камень огранки маркиз. Минимум деталей и очень узнаваемая геометрия — украшение для тех, кто любит современную лаконичность.',
                   hy='Հարթ ոսկե աղեղը մեղմորեն կրկնում է պարանոցի գիծը, իսկ նրա ստորին կետում ուղղահայաց ամրացված է մարկիզ հղկվածքի քար։ Նվազագույն մանրամասներ և շատ ճանաչելի երկրաչափություն։',
                   en='A smooth gold arc gently follows the line of the neck, with a marquise-cut stone set vertically at its lowest point. Minimal detail and a very recognisable geometry.'),
         tags=dict(ru=['маркиз', 'колье', 'минимализм'], hy=['մարկիզ', 'վզնոց', 'մինիմալիզմ'], en=['marquise', 'necklace', 'minimal'])),

    # ---------------------------- подвески ----------------------------
    dict(src=21, id='butterfly-glow-pendant', cat='pendants', label='Подвески', col='Papillon',
         mat=MAT_Y, st=ST_PAVE, size='Ширина ок. 18 мм',
         name=dict(ru='Подвеска Butterfly Glow', hy='Կախազարդ Butterfly Glow', en='Butterfly Glow Pendant'),
         short=dict(ru='Объемные крылья и тельце в мелком паве.',
                    hy='Ծավալուն թևեր և մարմին՝ մանր պավեով.',
                    en='Sculpted wings with a pavé body.'),
         desc=dict(ru='Крылья вылеплены округлыми полированными линиями, а каплевидное тельце полностью усыпано мелкими камнями и подвешено на подвижном колечке — при движении бабочка слегка покачивается и ловит свет.',
                   hy='Թևերը ձևավորված են կլորացված փայլեցված գծերով, իսկ կաթիլաձև մարմինը ամբողջությամբ ծածկված է մանր քարերով և կախված է շարժական օղակից՝ շարժման ժամանակ թիթեռը թեթևակի օրորվում է։',
                   en='The wings are modelled in rounded polished lines, while the drop-shaped body is fully set with small stones and hangs from a moving loop, so the butterfly sways and catches the light.'),
         tags=dict(ru=['бабочка', 'паве', 'подарок'], hy=['թիթեռ', 'պավե', 'նվեր'], en=['butterfly', 'pavé', 'gift'])),

    dict(src=23, id='butterfly-trio-pendant', cat='pendants', label='Подвески', col='Papillon',
         mat=MAT_Y, st=ST_PAVE, size='Высота ок. 35 мм',
         name=dict(ru='Подвеска Butterfly Trio', hy='Կախազարդ Butterfly Trio', en='Butterfly Trio Pendant'),
         short=dict(ru='Каскад из четырех бабочек разного размера.',
                    hy='Չորս տարբեր չափի թիթեռների կասկադ.',
                    en='A cascade of four butterflies of different sizes.'),
         desc=dict(ru='Бабочки закреплены на подвижных звеньях и спускаются каскадом — крупные сверху, маленькие ниже. Крылья полностью покрыты камнями, поэтому даже небольшое движение дает живой, рассыпчатый блеск.',
                   hy='Թիթեռները ամրացված են շարժական օղակներին և իջնում են կասկադով՝ խոշորները վերևում, փոքրերը ներքևում։ Թևերը ամբողջությամբ ծածկված են քարերով, ուստի նույնիսկ փոքր շարժումը տալիս է կենդանի փայլ։',
                   en='The butterflies hang from moving links in a cascade — larger above, smaller below. The wings are fully set with stones, so even a slight movement creates a lively, scattered sparkle.'),
         tags=dict(ru=['бабочка', 'каскад', 'эффектно'], hy=['թիթեռ', 'կասկադ', 'տպավորիչ'], en=['butterfly', 'cascade', 'statement'])),

    dict(src=26, id='laurel-circle-pendant', cat='pendants', label='Подвески', col='Signature Gold',
         mat=MAT_Y, st=ST_PAVE, size='Диаметр ок. 22 мм',
         name=dict(ru='Подвеска Laurel', hy='Կախազարդ Laurel', en='Laurel Pendant'),
         short=dict(ru='Кольцо из лавровой ветви с листьями в паве.',
                    hy='Դափնու ճյուղի օղակ՝ պավե տերևներով.',
                    en='A laurel branch circle with pavé leaves.'),
         desc=dict(ru='Ветвь свернута в круг: полированный стебель идет по кольцу, а листья, закрепленные мелкими камнями, расходятся в стороны. Открытая середина делает подвеску легкой, несмотря на крупный диаметр.',
                   hy='Ճյուղը ոլորված է շրջանի մեջ․ փայլեցված ցողունն անցնում է օղակով, իսկ մանր քարերով ամրացված տերևները բացվում են կողքերին։ Բաց միջուկը կախազարդը դարձնում է թեթև։',
                   en='The branch is curled into a circle: the polished stem follows the ring while the stone-set leaves spread outwards. The open middle keeps the pendant light despite its diameter.'),
         tags=dict(ru=['лавр', 'круг', 'символ'], hy=['դափնի', 'շրջան', 'խորհրդանիշ'], en=['laurel', 'circle', 'symbol'])),

    dict(src=28, id='clover-pendant', cat='pendants', label='Подвески', col='Fleur',
         mat=MAT_Y, st=ST_PAVE, size='Ширина ок. 20 мм',
         name=dict(ru='Подвеска Clover', hy='Կախազարդ Clover', en='Clover Pendant'),
         short=dict(ru='Четырехлистник с камнями на концах лепестков.',
                    hy='Քառաթերթիկ՝ ծայրերին քարերով.',
                    en='A four-petal clover with stones at the tips.'),
         desc=dict(ru='Четыре остроконечных лепестка образуют открытый цветок-клевер. На конце каждого лепестка закреплены по три круглых камня, а сами линии оставлены гладкими и полированными — получается чистая графика с точечным блеском.',
                   hy='Չորս սրածայր թերթիկ կազմում են բաց երեքնուկ-ծաղիկ։ Յուրաքանչյուր թերթիկի ծայրին ամրացված են երեք կլոր քար, իսկ գծերը մնացել են հարթ և փայլեցված։',
                   en='Four pointed petals form an open clover. Three round stones sit at the tip of each petal while the lines stay smooth and polished — clean graphics with pinpoint sparkle.'),
         tags=dict(ru=['клевер', 'на удачу', 'подарок'], hy=['երեքնուկ', 'հաջողության', 'նվեր'], en=['clover', 'luck', 'gift'])),

    dict(src=9, id='giraffe-gold-pendant', cat='pendants', label='Подвески', col='Little Gold',
         mat=MAT_Y, st='Черные вставки-кабошоны', size='Высота ок. 28 мм',
         name=dict(ru='Подвеска Жирафик', hy='Կախազարդ Ընձուղտիկ', en='Little Giraffe Pendant'),
         short=dict(ru='Детская подвеска с матовым корпусом и пятнышками.',
                    hy='Մանկական կախազարդ՝ մատ մարմնով և բծերով.',
                    en="A children's pendant with a matte body and spots."),
         desc=dict(ru='Корпус жирафа сделан матовым, а круглые пятна, рожки и копытца — полированными, поэтому фигурка выглядит объемной. Глаз и кончики рожек отмечены темными кабошонами. Отличный подарок на рождение или первый день рождения.',
                   hy='Ընձուղտի մարմինը մատ է, իսկ կլոր բծերը, եղջյուրները և սմբակները՝ փայլեցված, ուստի արձանիկը երևում է ծավալուն։ Աչքը և եղջյուրների ծայրերը նշված են մուգ կաբոշոններով։ Հիանալի նվեր ծննդյան առթիվ։',
                   en='The giraffe’s body is matte while the round spots, horns and hooves are polished, giving the figure depth. The eye and horn tips are marked with dark cabochons. A lovely new-baby or first-birthday gift.'),
         tags=dict(ru=['детское', 'жираф', 'подарок'], hy=['մանկական', 'ընձուղտ', 'նվեր'], en=['kids', 'giraffe', 'gift'])),

    dict(src=13, id='giraffe-duo-pendant', cat='pendants', label='Подвески', col='Little Gold',
         mat=MAT_W, st=ST_SOLO, size='Высота ок. 26 мм',
         name=dict(ru='Подвеска Жираф с малышом', hy='Կախազարդ Ընձուղտը ձագով', en='Giraffe and Baby Pendant'),
         short=dict(ru='Ажурный силуэт мамы и малыша с одним камнем.',
                    hy='Մոր և ձագի ажурային ուրվագիծ՝ մեկ քարով.',
                    en='An openwork mother-and-baby silhouette with one stone.'),
         desc=dict(ru='Две фигуры нарисованы одной непрерывной линией: шея мамы-жирафа превращается в контур малыша, который тянется к ней. Внутри корпуса — завитки вместо пятен, а голова малыша отмечена камнем. Подвеска-символ связи мамы и ребенка.',
                   hy='Երկու կերպարները գծված են մեկ անընդհատ գծով․ մայր ընձուղտի պարանոցը վերածվում է ձագի ուրվագծի, որը ձգվում է դեպի նա։ Մարմնի ներսում՝ ոլորաններ բծերի փոխարեն, իսկ ձագի գլուխը նշված է քարով։',
                   en='Both figures are drawn with one continuous line: the mother’s neck becomes the outline of the baby reaching towards her. Scrolls replace the spots inside the body and a stone marks the baby’s head — a symbol of the bond between mother and child.'),
         tags=dict(ru=['детское', 'мама и малыш', 'белое золото'], hy=['մանկական', 'մայր և ձագ', 'սպիտակ ոսկի'], en=['kids', 'mother and baby', 'white gold'])),

    # ---------------------------- серьги ----------------------------
    dict(src=12, id='butterfly-huggie-earrings', cat='earrings', label='Серьги', col='Papillon',
         mat=MAT_Y, st=ST_PAVE, size='Диаметр ок. 12 мм',
         name=dict(ru='Серьги Butterfly Huggie', hy='Ականջօղեր Butterfly Huggie', en='Butterfly Huggie Earrings'),
         short=dict(ru='Мини-конго с бабочкой, полностью в камнях.',
                    hy='Մինի-կոնգո թիթեռով՝ ամբողջությամբ քարերով.',
                    en='Mini hoops with a fully pavé butterfly.'),
         desc=dict(ru='Небольшое плотное кольцо-конго с надежным щелчковым замком, а спереди — бабочка, крылья которой целиком закреплены мелкими камнями. Серьги сидят близко к мочке, не мешают и подходят для ежедневного ношения.',
                   hy='Փոքր ամուր կոնգո-օղակ՝ հուսալի սեղմիչ կողպեքով, իսկ առջևում՝ թիթեռ, որի թևերն ամբողջությամբ ամրացված են մանր քարերով։ Ականջօղերը նստում են ականջին մոտ և հարմար են ամենօրյա կրելու համար։',
                   en='A small, snug hoop with a secure click clasp and, at the front, a butterfly whose wings are entirely set with small stones. They sit close to the lobe and are comfortable for daily wear.'),
         tags=dict(ru=['серьги', 'бабочка', 'на каждый день'], hy=['ականջօղեր', 'թիթեռ', 'ամենօրյա'], en=['earrings', 'butterfly', 'everyday'])),

    # ---------------------------- браслеты ----------------------------
    dict(src=1, id='tennis-classic-bracelet', cat='bracelets', label='Браслеты', col='Tennis',
         mat=MAT_W, st=ST_LINE, size='17–19 см',
         name=dict(ru='Браслет Tennis Classic', hy='Ապարանջան Tennis Classic', en='Tennis Classic Bracelet'),
         short=dict(ru='Ровная дорожка круглых камней по всей длине.',
                    hy='Կլոր քարերի հավասար շարք ամբողջ երկարությամբ.',
                    en='An even line of round stones all the way round.'),
         desc=dict(ru='Классический теннисный браслет: одинаковые круглые камни в четырех лапках, звено к звену, с гибким соединением и плоским замком-коробочкой с предохранителем. Садится по руке мягко и сияет непрерывной линией.',
                   hy='Դասական թենիսային ապարանջան․ միանման կլոր քարեր չորս ճանկերում, օղակ առ օղակ, ճկուն միացումով և ապահովիչով հարթ կողպեքով։ Նստում է ձեռքին մեղմ և փայլում անընդհատ գծով։',
                   en='A classic tennis bracelet: identical round stones in four prongs, link after link, with a flexible articulation and a flat box clasp with a safety catch. It drapes softly and shines in one continuous line.'),
         tags=dict(ru=['теннис', 'браслет', 'вечерний образ'], hy=['թենիս', 'ապարանջան', 'երեկոյան'], en=['tennis', 'bracelet', 'evening'])),

    dict(src=3, id='laurel-marquise-bracelet', cat='bracelets', label='Браслеты', col='Royal Detail',
         mat=MAT_W, st='Камни огранки маркиз', size='17–19 см',
         name=dict(ru='Браслет Laurel', hy='Ապարանջան Laurel', en='Laurel Bracelet'),
         short=dict(ru='Два ряда камней маркиз, уложенных колоском.',
                    hy='Մարկիզ քարերի երկու շարք՝ հասկաձև.',
                    en='Two rows of marquise stones laid like a wheat ear.'),
         desc=dict(ru='Камни огранки маркиз закреплены под углом в два встречных ряда — получается узор колоска или лаврового венка. Браслет заметно шире классического теннисного и держит форму, оставаясь подвижным.',
                   hy='Մարկիզ հղկվածքի քարերը ամրացված են անկյան տակ՝ երկու հանդիպակաց շարքով, ինչը ստեղծում է հասկի կամ դափնու պսակի նախշ։ Ապարանջանն ավելի լայն է դասականից և պահում է ձևը՝ մնալով շարժուն։',
                   en='Marquise-cut stones are set at an angle in two opposing rows, creating a wheat-ear or laurel-wreath pattern. Noticeably wider than a classic tennis line, it keeps its shape yet stays flexible.'),
         tags=dict(ru=['маркиз', 'браслет', 'эффектно'], hy=['մարկիզ', 'ապարանջան', 'տպավորիչ'], en=['marquise', 'bracelet', 'statement'])),

    dict(src=4, id='marquise-tennis-bracelet', cat='bracelets', label='Браслеты', col='Tennis',
         mat=MAT_W, st='Камни огранки маркиз', size='17–19 см',
         name=dict(ru='Браслет Marquise Tennis', hy='Ապարանջան Marquise Tennis', en='Marquise Tennis Bracelet'),
         short=dict(ru='Крупные камни маркиз, уложенные по диагонали.',
                    hy='Խոշոր մարկիզ քարեր՝ անկյունագծով.',
                    en='Large marquise stones set on the diagonal.'),
         desc=dict(ru='Один ряд вытянутых камней, повернутых по диагонали, — за счет наклона линия выглядит мягкой и будто течет по запястью. Каждый камень держат четыре лапки, замок плоский, с дополнительной защелкой.',
                   hy='Մեկ շարք երկարավուն քարեր՝ շրջված անկյունագծով․ թեքության շնորհիվ գիծը երևում է մեղմ և կարծես հոսում է դաստակով։ Յուրաքանչյուր քար պահում են չորս ճանկեր, կողպեքը հարթ է՝ լրացուցիչ ամրակով։',
                   en='A single row of elongated stones turned on the diagonal — the tilt makes the line look soft, as if it flowed around the wrist. Four prongs hold every stone; the clasp is flat with an extra latch.'),
         tags=dict(ru=['маркиз', 'теннис', 'браслет'], hy=['մարկիզ', 'թենիս', 'ապարանջան'], en=['marquise', 'tennis', 'bracelet'])),
]

# общие значения характеристик (переводы добавляются один раз)
COMMON = {
    'Золото 585 / 750': dict(hy='Ոսկի 585 / 750', en='Gold 585 / 750'),
    'Белое золото 585': dict(hy='Սպիտակ ոսկի 585', en='White gold 585'),
    'Красное золото 585': dict(hy='Կարմիր ոսկի 585', en='Rose gold 585'),
    'Бриллианты или фианиты, паве': dict(hy='Ադամանդներ կամ ֆիանիտներ, պավե', en='Diamonds or cubic zirconia, pavé'),
    'Центральный камень и паве': dict(hy='Կենտրոնական քար և պավե', en='Centre stone and pavé'),
    'Один центральный камень': dict(hy='Մեկ կենտրոնական քար', en='One centre stone'),
    'Дорожка камней по всей длине': dict(hy='Քարերի շարք ամբողջ երկարությամբ', en='A line of stones all the way round'),
    'Камни огранки маркиз': dict(hy='Մարկիզ հղկվածքի քարեր', en='Marquise-cut stones'),
    'Черные вставки-кабошоны': dict(hy='Սև կաբոշոն ներդիրներ', en='Black cabochon accents'),
    'Высота ок. 25 мм': dict(hy='Բարձրությունը մոտ 25 մմ', en='Height approx. 25 mm'),
    'Высота ок. 24 мм': dict(hy='Բարձրությունը մոտ 24 մմ', en='Height approx. 24 mm'),
    'Высота ок. 28 мм': dict(hy='Բարձրությունը մոտ 28 մմ', en='Height approx. 28 mm'),
    'Высота ок. 26 мм': dict(hy='Բարձրությունը մոտ 26 մմ', en='Height approx. 26 mm'),
    'Высота ок. 38 мм': dict(hy='Բարձրությունը մոտ 38 մմ', en='Height approx. 38 mm'),
    'Высота ок. 32 мм': dict(hy='Բարձրությունը մոտ 32 մմ', en='Height approx. 32 mm'),
    'Высота ок. 35 мм': dict(hy='Բարձրությունը մոտ 35 մմ', en='Height approx. 35 mm'),
    'Высота ок. 27 мм': dict(hy='Բարձրությունը մոտ 27 մմ', en='Height approx. 27 mm'),
    'Ширина ок. 18 мм': dict(hy='Լայնությունը մոտ 18 մմ', en='Width approx. 18 mm'),
    'Ширина ок. 20 мм': dict(hy='Լայնությունը մոտ 20 մմ', en='Width approx. 20 mm'),
    'Диаметр ок. 22 мм': dict(hy='Տրամագիծը մոտ 22 մմ', en='Diameter approx. 22 mm'),
    'Диаметр ок. 12 мм': dict(hy='Տրամագիծը մոտ 12 մմ', en='Diameter approx. 12 mm'),
    'Цепочка 40–45 см': dict(hy='Շղթա 40–45 սմ', en='Chain 40–45 cm'),
    '17–19 см': dict(hy='17–19 սմ', en='17–19 cm'),
    'Колье': dict(hy='Վզնոցներ', en='Necklaces'),
    'Подвески': dict(hy='Կախազարդեր', en='Pendants'),
    'Серьги': dict(hy='Ականջօղեր', en='Earrings'),
    'Браслеты': dict(hy='Ապարանջաններ', en='Bracelets'),
    'По расчету': dict(hy='Ըստ հաշվարկի', en='Calculated per piece'),
    'В наличии и под заказ': dict(hy='Առկա է և պատվերով', en='In stock and made to order'),
    'Цена по запросу': dict(hy='Գինը՝ հարցումով', en='Price on request'),
    'Sacred Light': dict(hy='Sacred Light', en='Sacred Light'),
    'Papillon': dict(hy='Papillon', en='Papillon'),
    'Fleur': dict(hy='Fleur', en='Fleur'),
    'Little Gold': dict(hy='Little Gold', en='Little Gold'),
}
